before_install:
- openssl aes-256-cbc -K $encrypted_25a94f7b27d4_key -iv $encrypted_25a94f7b27d4_iv
  -in 4790189186.enc -out ~/.ssh/4790189186 -d
script:
- sudo apt update
- chmod 600 ~/.ssh/4790189186
- eval `ssh-agent -s`
- ssh-add ~/.ssh/4790189186
- ssh root@47.90.189.186 -o StrictHostKeyChecking=no '/var/www/html/deploy.sh'